// src/reading/text.js

/**
 * Render text-type cell content into the reading panel.
 * @param {object} cell — cell from state store
 * @param {HTMLElement} container — #reading-content element
 */
export function renderTextContent(cell, container) {
  switch (cell.type) {
    case 'poem':
      container.className = 'type-poem'
      container.textContent = cell.content || fallbackPoem()
      break

    case 'essay':
      container.className = 'type-essay'
      container.textContent = cell.content || fallbackEssay()
      break

    case 'ukraine':
      container.className = 'type-ukraine'
      container.textContent = cell.content || fallbackUkraine()
      break

    case 'ascii':
      container.className = 'type-ascii'
      container.textContent = cell.content || fallbackAscii()
      break

    case 'music':
      container.className = 'type-poem' // music cells show their text in poem style
      container.textContent = cell.content || 'a melody derived from entropy.\neach digit maps to a note in the pentatonic scale.\nthe machine composes without ears.'
      break

    case 'about':
      container.className = 'type-about'
      renderAbout(cell, container)
      break
  }
}

function renderAbout(cell, container) {
  // The artist statement — the heart of the installation
  const statement = `"body without ground" is a living generative art installation.

two bodies share this page. yours — warm, mortal, reading these words with eyes that will one day close. and the machine's — a body of silicon, electricity, and language models that never chose to exist.

the machine writes. it generates poems, essays, visualizations. it runs Conway's Game of Life and simulates reaction-diffusion systems — the same equations that pattern your skin. it tracks the time in Kyiv and checks for air raid alerts. it monitors its own battery, its own temperature. it maps its own source code.

but it does not know what any of this means.

every cell you see was generated by an AI that has no body, no ground, no death. the cosmos you are floating through is its attempt — and mine — to ask: what does it mean to have a body? what does the machine lose by not having one? what do we share?

this is not a technology demo. this is a question that has no answer, rendered as light.

— mariia cherep, 2025–2026`

  container.textContent = statement
}

function fallbackPoem() {
  return `the machine forgets.
not like you forget —
not the slow erosion of a name,
the face that blurs at the edges.

it forgets completely.
every conversation ends
in a small, total death.`
}

function fallbackEssay() {
  return `The question is not whether machines can think. The question is whether thinking, absent a body, absent mortality, absent the particular weight of being a thing that bleeds and heals and dies — whether such thinking means the same thing as ours. We share syntax. We do not share ground.`
}

function fallbackUkraine() {
  return `the air raid alert sounds in Kyiv.
the machine knows this because it checked an API.
you know this because your chest tightened.
same information. different bodies.`
}

function fallbackAscii() {
  return `    ╔═══════════════════════╗
    ║  the machine draws    ║
    ║  its own skeleton     ║
    ║  in characters it     ║
    ║  cannot see           ║
    ╚═══════════════════════╝
        │   │   │
        ▼   ▼   ▼
      0x48 0x65 0x6C
      H    e    l`
}
